
export const GET_PASSENGER="GET_PASSENGER"
export const GET_ALLPASSENGER="GET_ALLPASSENGER"
export const GET_AIRLINE="GET_AIRLINE"
export const SELECT_DATA="SELECT_DATA"
export const PASSENGER_ADD="PASSENGER_ADD"
export const PASSENGER_UPDATE="PASSENGER_UPDATE"
export const PASSENGER_DELETE="PASSENGER_DELETE"
